// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qunglhmmcuomzsgqidoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bmdsaG1tY3VvbXpzZ3FpZG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Mzk0OTgsImV4cCI6MjA2NTAxNTQ5OH0.w42XsARHdFLqMxkpI_Nqgqmhm_-E9DhfVWnmeQG2VO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);